### ISSUE TITLE
还是字体乱码的问题，安装了但没有生效呢

### ISSUE THREAD

**Issue by everettjf** [dofy/7th-vim#3]
macOS 下按照 https://github.com/ryanoasis/nerd-fonts 的brew安装方法

```
brew tap caskroom/fonts
brew cask install font-hack-nerd-font
```

安装后文件列表文件名左侧还是乱码

![image](https://user-images.githubusercontent.com/1665109/34319125-d01ebaca-e814-11e7-8026-296a13fcd2e5.png)

**Comment by dofy** [comment]
要设置一下 terminal 的字体

**Comment by everettjf** [comment]
terminal.app设置Nerd字体后，可以了。
iTerm2.app 需要同时设置 Non-ascii font。
MacVim.app 需要在.gvimrc中设置字体：

```
$ cat .gvimrc
set guifont=Knack\ Nerd\ Font:h12
```

**Comment by dofy** [comment]
> **Warning**
> `caskroom/fonts` was moved. Tap `homebrew/cask-fonts` instead.
> and
> `brew cask` is no longer a `brew` command. Use `brew <command> --cask` instead.

> **Note**
> ```bash
> brew tap homebrew/cask-fonts
> brew install font-hack-nerd-font --cask
> ```
