### ISSUE TITLE
使用vim时报错`Invalid expression: > mkdp#util#install() } })`

### ISSUE THREAD

**Issue by Crazyokd** [dofy/7th-vim#8]
系统：Centos7.9
vim版本：VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 15 2020 16:44:08)

报错详细信息：
```
line  134:
E15: Invalid expression: > mkdp#util#install()},'for':'markdown' })
E116: Invalid arguments for function plug#
```

**Comment by Crazyokd** [comment]
系统：Centos7.9
vim版本：VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 15 2020 16:44:08)

**Comment by dofy** [comment]
请问是启动 vim 时就报错还是执行 markdown 预览时报错啊？

可以参考对应项目的配置适当修改下看看： https://github.com/iamcco/markdown-preview.nvim

**Comment by Crazyokd** [comment]
启动vim时报错。

**Comment by Crazyokd** [comment]
参考[https://github.com/iamcco/markdown-preview.nvim/issues/50#issuecomment-634073224](https://github.com/iamcco/markdown-preview.nvim/issues/50#issuecomment-634073224),将报错那一行改为`Plug 'iamcco/markdown-preview.nvim', { 'do': ':call mkdp#util#install()', 'for': 'markdown' }`就解决了。

**Comment by Crazyokd** [comment]
执行`:PlugStatus`查看了下，发现有两个插件没安装，将两个插件相继安装后，将上面那一行又修改为最初的代码，没有再报错。

**Comment by dofy** [comment]
> 执行`:PlugStatus`查看了下，发现有两个插件没安装，将两个插件相继安装后，将上面那一行又修改为最初的代码，没有再报错。

好，谢谢您的尝试，之前我这边 Mac 是没问题的，我试一下加上 for markdown 看看如果也没问题我更新一下代码。

**Comment by Crazyokd** [comment]
> 好，谢谢您的尝试，之前我这边 Mac 是没问题的，我试一下加上 for markdown 看看如果也没问题我更新一下代码。

建议您提供一个插件安装情况检测机制。
因为即使配置方案中的插件安装不完全，vim还是能够在启动时报错的情况下继续使用，如果报错之前没有插件管理器的经验将会对报错感到困惑不解（在报错之初我也没有该经验）

**Comment by dofy** [comment]
> > 好，谢谢您的尝试，之前我这边 Mac 是没问题的，我试一下加上 for markdown 看看如果也没问题我更新一下代码。
> 
> 建议您提供一个插件安装情况检测机制。 因为即使配置方案中的插件安装不完全，vim还是能够在启动时报错的情况下继续使用，如果报错之前没有插件管理器的经验将会对报错感到困惑不解（在报错之初我也没有该经验）

因为脚本在最初安装时默认提供全部定义的语言支持，会自动安装所有插件，所以没有进行检查，我研究一下看能不能加上检测脚本。
